//! The drawing's search sample data (menu-v22 `SDATA`, generated from the drawing): what a test copy's fake Windows holds (search.rs `sample_os`).

/// menu-v22 `SDATA` (the drawing's made-up search results; its user folder renamed "User"): kind, name, path, date,
/// size, tile (apps: the TAPP key; files: the TFILE key).
pub const SDATA: &[(&str, &str, &str, &str, &str, &str)] = &[
    (r"app", r"Discord", r"C:\Users\User\AppData\Local\Discord\Update.exe", r"", r"", r"discord"),
    (r"app", r"Steam", r"C:\Program Files (x86)\Steam\steam.exe", r"", r"", r"steam"),
    (r"app", r"VALORANT", r"C:\Riot Games\Riot Client\RiotClientServices.exe", r"", r"", r"val"),
    (r"app", r"Riot Client", r"C:\Riot Games\Riot Client\RiotClientServices.exe", r"", r"", r"riot"),
    (r"app", r"OBS Studio", r"C:\Program Files\obs-studio\bin\64bit\obs64.exe", r"", r"", r"obs"),
    (r"app", r"Spotify", r"C:\Users\User\AppData\Roaming\Spotify\Spotify.exe", r"", r"", r"spot"),
    (r"app", r"Google Chrome", r"C:\Program Files\Google\Chrome\Application\chrome.exe", r"", r"", r"chrome"),
    (r"app", r"Notepad", r"C:\Windows\System32\notepad.exe", r"", r"", r"note"),
    (r"app", r"Paint", r"C:\Program Files\WindowsApps\Microsoft.Paint\PaintApp\mspaint.exe", r"", r"", r"paint"),
    (r"app", r"Wootility", r"C:\Users\User\AppData\Local\Programs\wootility\Wootility.exe", r"", r"", r"woot"),
    (r"app", r"NVIDIA App", r"C:\Program Files\NVIDIA Corporation\NVIDIA App\CEF\NVIDIA App.exe", r"", r"", r"nv"),
    (r"app", r"Rocket League", r"C:\Program Files\Epic Games\rocketleague\Binaries\Win64\RocketLeague.exe", r"", r"", r"rl"),
    (r"app", r"Epic Games Launcher", r"C:\Program Files (x86)\Epic Games\Launcher\Portal\Binaries\Win64\EpicGamesLauncher.exe", r"", r"", r"epic"),
    (r"app", r"Visual Studio Code", r"C:\Users\User\AppData\Local\Programs\Microsoft VS Code\Code.exe", r"", r"", r"code"),
    (r"app", r"File Explorer", r"C:\Windows\explorer.exe", r"", r"", r"exp"),
    (r"app", r"Task Manager", r"C:\Windows\System32\Taskmgr.exe", r"", r"", r"win"),
    (r"app", r"Control Panel", r"C:\Windows\System32\control.exe", r"", r"", r"sys"),
    (r"app", r"Settings", r"ms-settings:", r"", r"", r"sys"),
    (r"app", r"Command Prompt", r"C:\Windows\System32\cmd.exe", r"", r"", r"win"),
    (r"app", r"Windows PowerShell", r"C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe", r"", r"", r"win"),
    (r"app", r"Snipping Tool", r"C:\Program Files\WindowsApps\Microsoft.ScreenSketch\SnippingTool\SnippingTool.exe", r"", r"", r"win"),
    (r"app", r"Calculator", r"C:\Program Files\WindowsApps\Microsoft.WindowsCalculator\CalculatorApp.exe", r"", r"", r"calc"),
    (r"app", r"VLC media player", r"C:\Program Files\VideoLAN\VLC\vlc.exe", r"", r"", r"vlc"),
    (r"app", r"7-Zip File Manager", r"C:\Program Files\7-Zip\7zFM.exe", r"", r"", r"zip"),
    (r"app", r"Device Manager", r"C:\Windows\System32\devmgmt.msc", r"", r"", r"sys"),
    (r"app", r"Sound settings", r"ms-settings:sound", r"", r"", r"sys"),
    (r"dir", r"Downloads", r"C:\Users\User\Downloads", r"2 Oct 2026", r"214 items", r""),
    (r"dir", r"Documents", r"C:\Users\User\Documents", r"6 Oct 2026", r"58 items", r""),
    (r"dir", r"Pictures", r"C:\Users\User\Pictures", r"6 Oct 2026", r"31 items", r""),
    (r"dir", r"Screenshots", r"C:\Users\User\Pictures\Screenshots", r"6 Oct 2026", r"412 items", r""),
    (r"dir", r"Videos", r"C:\Users\User\Videos", r"5 Oct 2026", r"12 items", r""),
    (r"dir", r"Clips", r"C:\Users\User\Desktop\Clips", r"6 Oct 2026", r"96 items", r""),
    (r"dir", r"VALORANT", r"C:\Riot Games\VALORANT", r"1 Oct 2026", r"6 items", r""),
    (r"dir", r"Rocket League", r"C:\Users\User\Documents\My Games\Rocket League", r"29 Sep 2026", r"3 items", r""),
    (r"dir", r"Recordings", r"D:\Recordings", r"6 Oct 2026", r"148 items", r""),
    (r"dir", r"steamapps", r"C:\Program Files (x86)\Steam\steamapps", r"4 Oct 2026", r"9 items", r""),
    (r"dir", r"cfg", r"C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\game\csgo\cfg", r"30 Sep 2026", r"41 items", r""),
    (r"dir", r"Wallpapers", r"C:\Users\User\Pictures\Wallpapers", r"12 Aug 2026", r"27 items", r""),
    (r"dir", r"School", r"C:\Users\User\Documents\School", r"18 Sep 2026", r"23 items", r""),
    (r"file", r"valorant_ace_2026-10-06.mp4", r"C:\Users\User\Videos", r"6 Oct 2026", r"84.2 MB", r"vid"),
    (r"file", r"rl_freestyle_reset.mp4", r"D:\Recordings", r"4 Oct 2026", r"212.7 MB", r"vid"),
    (r"file", r"Screenshot 2026-10-06 214512.png", r"C:\Users\User\Pictures\Screenshots", r"6 Oct 2026", r"1.4 MB", r"pic"),
    (r"file", r"Screenshot 2026-10-05 193108.png", r"C:\Users\User\Pictures\Screenshots", r"5 Oct 2026", r"2.1 MB", r"pic"),
    (r"file", r"wallpaper_ultrawide_3440x1440.jpg", r"C:\Users\User\Pictures\Wallpapers", r"12 Aug 2026", r"3.8 MB", r"pic"),
    (r"file", r"setup_photo.jpg", r"C:\Users\User\Pictures", r"30 Sep 2026", r"2.6 MB", r"pic"),
    (r"file", r"autoexec.cfg", r"C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\game\csgo\cfg", r"30 Sep 2026", r"2 KB", r"cfg"),
    (r"file", r"TASystemSettings.ini", r"C:\Users\User\Documents\My Games\Rocket League\TAGame\Config", r"29 Sep 2026", r"4 KB", r"cfg"),
    (r"file", r"invoice_september.pdf", r"C:\Users\User\Documents", r"2 Oct 2026", r"212 KB", r"doc"),
    (r"file", r"resume_2026.docx", r"C:\Users\User\Documents", r"18 Sep 2026", r"36 KB", r"doc"),
    (r"file", r"school_project_final.pptx", r"C:\Users\User\Documents\School", r"25 Sep 2026", r"8.9 MB", r"doc"),
    (r"file", r"notes.txt", r"C:\Users\User\Desktop", r"6 Oct 2026", r"3 KB", r"txt"),
    (r"file", r"game settings backup.txt", r"C:\Users\User\Documents", r"1 Oct 2026", r"6 KB", r"txt"),
    (r"file", r"OBS-Studio-31.0.3-Windows-Installer.exe", r"C:\Users\User\Downloads", r"2 Oct 2026", r"142.6 MB", r"exe"),
    (r"file", r"DiscordSetup.exe", r"C:\Users\User\Downloads", r"27 Sep 2026", r"96.1 MB", r"exe"),
    (r"file", r"clips_backup.zip", r"D:\Backups", r"20 Sep 2026", r"1.8 GB", r"zip"),
    (r"file", r"steam_screenshot_rl.jpg", r"C:\Users\User\Pictures", r"28 Sep 2026", r"1.1 MB", r"pic"),
    (r"file", r"valorant_settings.txt", r"C:\Users\User\Documents", r"3 Oct 2026", r"2 KB", r"txt"),
    (r"file", r"discord_voice_test.mp4", r"C:\Users\User\Videos", r"26 Sep 2026", r"12.4 MB", r"vid"),
];
