//! The capture overlay's emoji (menu-v22 EMO_QUICK / EMO_DATA / ETAB, word for word - generated from the drawing by Lane Q's
//! scratch gen_emoji.py; do not edit by hand). Each entry: the emoji, then the words the search matches. Country flags are left out
//! (Windows' emoji font shows them as two letters).

/// The quick row the overlay starts with (the most used).
pub const QUICK: [&str; 8] = ["😂", "💀", "🔥", "👍", "❤️", "👀", "😭", "🤔"];

/// A category: id (its tab icon), name, the entries `"<emoji> <words>"` joined by `|`.
pub const DATA: [(&str, &str, &str); 8] = [
    ("smile", "Smileys", "😀 grinning happy|😃 smiley happy big|😄 smile happy|😁 grin beaming|😆 laughing lol|😅 sweat smile relief|🤣 rofl rolling laughing|😂 joy tears laughing lol|🙂 slight smile|🙃 upside down silly|😉 wink|😊 blush smile happy|😇 angel innocent halo|🥰 love hearts adore|😍 heart eyes love|🤩 star struck wow|😘 kiss blow love|😗 kissing|😚 kissing closed eyes|😙 kissing smiling|😋 yum tasty tongue|😛 tongue out|😜 wink tongue crazy|🤪 zany crazy goofy|😝 squint tongue|🤑 money rich|🤗 hug hugging|🤭 oops giggle hand mouth|🤫 shush quiet secret|🤔 thinking hmm|🤐 zipper mouth secret|🤨 raised eyebrow sus|😐 neutral meh|😑 expressionless|😶 no mouth speechless|😏 smirk|😒 unamused meh|🙄 eye roll|😬 grimace awkward|🤥 lying pinocchio|😌 relieved calm|😔 pensive sad|😪 sleepy|🤤 drooling|😴 sleeping zzz|😷 mask sick|🤒 thermometer sick ill|🤕 bandage hurt|🤢 nauseated sick|🤮 vomit puke|🤧 sneeze cold|🥵 hot sweating|🥶 cold freezing|🥴 woozy dizzy drunk|😵 dizzy knocked out|🤯 mind blown exploding|🤠 cowboy|🥳 party celebrate|😎 cool sunglasses|🤓 nerd glasses|🧐 monocle curious|😕 confused|😟 worried|🙁 slight frown|☹️ frown sad|😮 open mouth wow|😯 hushed surprised|😲 astonished shocked|😳 flushed embarrassed|🥺 pleading puppy eyes|😦 frowning|😧 anguished|😨 fearful scared|😰 anxious sweat|😥 sad relieved|😢 cry tear sad|😭 sob crying loud|😱 scream fear|😖 confounded|😣 persevere|😞 disappointed|😓 downcast sweat|😩 weary tired|😫 tired exhausted|🥱 yawn bored tired|😤 triumph huff angry|😡 pout rage angry|😠 angry mad|🤬 cursing swearing|😈 smiling devil evil|👿 angry devil imp|💀 skull dead lol|☠️ skull crossbones danger|💩 poop|🤡 clown|👹 ogre monster|👺 goblin|👻 ghost boo|👽 alien|👾 space invader game|🤖 robot|😺 cat smile|😸 cat grin|😹 cat joy tears|😻 cat heart eyes|😼 cat smirk|😽 cat kiss|🙀 cat weary scream|😿 cat crying|😾 cat pouting"),
    ("people", "People & hands", "👋 wave hello bye|🤚 raised back hand|🖐️ hand fingers splayed|✋ raised hand stop high five|🖖 vulcan salute|👌 ok perfect|🤌 pinched fingers|🤏 pinching small|✌️ victory peace|🤞 crossed fingers luck|🤟 love you gesture|🤘 rock on horns metal|🤙 call me shaka|👈 point left|👉 point right|👆 point up|👇 point down|☝️ index up one|🖕 middle finger|👍 thumbs up like yes|👎 thumbs down dislike no|✊ raised fist|👊 fist bump punch|🤛 left fist|🤜 right fist|👏 clap applause|🙌 raising hands hooray|👐 open hands|🤲 palms up|🤝 handshake deal|🙏 pray please thanks|✍️ writing|💅 nail polish|🤳 selfie|💪 muscle strong flex|🦾 mechanical arm|🦵 leg kick|🦶 foot|👂 ear listen|👃 nose smell|🧠 brain smart|🦷 tooth|🦴 bone|👀 eyes look|👁️ eye|👅 tongue|👄 mouth lips|💋 kiss mark lips|👶 baby|🧒 child kid|👦 boy|👧 girl|🧑 person|👨 man|👩 woman|🧓 older person|👴 old man|👵 old woman|🙋 raising hand|🙅 no gesture|🙆 ok gesture|💁 tipping hand|🤷 shrug idk|🤦 facepalm|🙇 bow sorry|💆 massage|🏃 running run|🚶 walking walk|💃 dancing woman dance|🕺 dancing man dance|👯 bunny dancers|🧘 yoga meditate|🛀 bath|👪 family|👫 couple holding hands|💑 couple heart|👮 police officer cop|🕵️ detective spy|💂 guard|👷 construction worker|🤴 prince|👸 princess|🦸 superhero hero|🦹 supervillain villain|🧙 mage wizard|🧚 fairy|🧛 vampire|🧜 merperson mermaid|🧝 elf|🧟 zombie|🥷 ninja|🎅 santa christmas|🤶 mrs claus"),
    ("heart", "Hearts", "❤️ red heart love|🧡 orange heart|💛 yellow heart|💚 green heart|💙 blue heart|💜 purple heart|🤎 brown heart|🖤 black heart|🤍 white heart|💔 broken heart|❣️ heart exclamation|💕 two hearts love|💞 revolving hearts|💓 beating heart|💗 growing heart|💖 sparkling heart|💘 heart arrow cupid|💝 heart ribbon gift|💟 heart decoration|♥️ heart suit cards|💌 love letter|💏 kiss couple|💐 bouquet flowers|🌹 rose|💍 ring wedding"),
    ("animal", "Animals & nature", "🐶 dog puppy|🐱 cat kitten|🐭 mouse|🐹 hamster|🐰 rabbit bunny|🦊 fox|🐻 bear|🐼 panda|🐨 koala|🐯 tiger|🦁 lion|🐮 cow|🐷 pig|🐸 frog|🐵 monkey|🙈 see no evil monkey|🙉 hear no evil monkey|🙊 speak no evil monkey|🐔 chicken|🐧 penguin|🐦 bird|🐤 chick|🦆 duck|🦅 eagle|🦉 owl|🦇 bat|🐺 wolf|🐗 boar|🐴 horse|🦄 unicorn|🐝 bee|🐛 bug caterpillar|🦋 butterfly|🐌 snail|🐞 ladybug|🐜 ant|🕷️ spider|🦂 scorpion|🐢 turtle|🐍 snake|🦎 lizard|🦖 t rex dinosaur|🦕 dinosaur|🐙 octopus|🦑 squid|🦐 shrimp|🦀 crab|🐡 blowfish|🐠 tropical fish|🐟 fish|🐬 dolphin|🐳 whale|🦈 shark|🐊 crocodile|🦓 zebra|🦍 gorilla|🐘 elephant|🦒 giraffe|🦘 kangaroo|🐪 camel|🐑 sheep|🐐 goat|🦌 deer|🐓 rooster|🦃 turkey|🦚 peacock|🦜 parrot|🦢 swan|🦩 flamingo|🦝 raccoon|🦨 skunk|🦦 otter|🦥 sloth|🐀 rat|🐿️ chipmunk squirrel|🦔 hedgehog|🐾 paw prints|🐉 dragon|🌵 cactus|🎄 christmas tree|🌲 evergreen tree|🌳 tree|🌴 palm tree|🌱 seedling plant|🌿 herb|🍀 four leaf clover luck|🍁 maple leaf|🍂 fallen leaves autumn|🌾 rice sheaf|🌷 tulip|🥀 wilted flower|🌺 hibiscus|🌸 cherry blossom|🌼 blossom|🌻 sunflower|🌞 sun face|🌝 moon face|🌚 new moon face|🌙 crescent moon|⭐ star|🌟 glowing star|✨ sparkles|⚡ lightning zap|🔥 fire lit hot|🌈 rainbow|☀️ sun|⛅ cloud sun|☁️ cloud|🌧️ rain|⛈️ storm thunder|❄️ snowflake|☃️ snowman|🌊 wave ocean|💧 droplet water|🌍 earth globe world"),
    ("food", "Food & drink", "🍏 green apple|🍎 apple|🍐 pear|🍊 orange tangerine|🍋 lemon|🍌 banana|🍉 watermelon|🍇 grapes|🍓 strawberry|🍈 melon|🍒 cherries|🍑 peach|🥭 mango|🍍 pineapple|🥥 coconut|🥝 kiwi|🍅 tomato|🍆 eggplant|🥑 avocado|🥦 broccoli|🥬 leafy green|🥒 cucumber|🌶️ hot pepper chili|🌽 corn|🥕 carrot|🧄 garlic|🧅 onion|🥔 potato|🥐 croissant|🥯 bagel|🍞 bread|🥖 baguette|🥨 pretzel|🧀 cheese|🥚 egg|🍳 cooking fried egg|🥞 pancakes|🧇 waffle|🥓 bacon|🥩 steak meat|🍗 chicken leg|🍖 meat bone|🌭 hot dog|🍔 burger hamburger|🍟 fries|🍕 pizza|🥪 sandwich|🌮 taco|🌯 burrito|🥙 kebab pita|🧆 falafel|🥗 salad|🍝 spaghetti pasta|🍜 ramen noodles|🍲 stew pot|🍛 curry|🍣 sushi|🍱 bento|🥟 dumpling|🍤 fried shrimp|🍙 rice ball|🍚 rice|🍥 fish cake|🍡 dango|🍧 shaved ice|🍨 ice cream|🍦 soft serve ice cream|🥧 pie|🧁 cupcake|🍰 cake slice|🎂 birthday cake|🍮 custard pudding|🍭 lollipop|🍬 candy|🍫 chocolate|🍿 popcorn|🍩 donut doughnut|🍪 cookie|🌰 chestnut|🥜 peanuts|🍯 honey|🥛 milk|🍼 baby bottle|☕ coffee hot|🍵 tea|🧃 juice box|🥤 cup soda|🧋 bubble tea|🍶 sake|🍺 beer|🍻 cheers beers|🥂 champagne toast|🍷 wine|🥃 whiskey|🍸 cocktail|🍹 tropical drink|🧉 mate|🍾 bottle popping champagne|🧊 ice cube|🥄 spoon|🍴 fork knife|🍽️ plate|🥢 chopsticks|🧂 salt"),
    ("sport", "Sports & games", "⚽ soccer football|🏀 basketball|🏈 american football|⚾ baseball|🥎 softball|🎾 tennis|🏐 volleyball|🏉 rugby|🥏 frisbee|🎱 pool 8 ball billiards|🏓 ping pong table tennis|🏸 badminton|🏒 ice hockey|🏑 field hockey|🥍 lacrosse|🏏 cricket|🥅 goal net|⛳ golf flag|🏹 bow arrow|🎣 fishing|🤿 diving mask|🥊 boxing glove|🥋 martial arts|🎽 running shirt|🛹 skateboard|🛼 roller skate|🛷 sled|⛸️ ice skate|🥌 curling|🎿 ski|⛷️ skier|🏂 snowboard|🏋️ weight lifting gym|🤼 wrestling|🤸 cartwheel|⛹️ bouncing ball|🤺 fencing|🤾 handball|🏌️ golfing|🏇 horse racing|🧗 climbing|🏄 surfing|🏊 swimming|🤽 water polo|🚣 rowing boat|🚴 biking cycling|🚵 mountain bike|🏆 trophy win cup|🥇 gold medal first|🥈 silver medal second|🥉 bronze medal third|🏅 medal|🎖️ military medal|🏵️ rosette|🎗️ reminder ribbon|🎫 ticket|🎟️ admission tickets|🎪 circus tent|🎭 theater masks|🎨 art palette paint|🎬 clapper movie film|🎤 microphone sing karaoke|🎧 headphones music|🎼 music score|🎹 piano keyboard|🥁 drum|🎷 saxophone|🎺 trumpet|🎸 guitar|🎻 violin|🎲 dice game|♟️ chess pawn|🎯 bullseye target dart|🎳 bowling|🎮 video game controller gaming|🕹️ joystick arcade|🎰 slot machine|🧩 puzzle piece|🎉 party popper tada|🎊 confetti ball|🎈 balloon|🎁 gift present|🎀 ribbon bow|🎃 pumpkin halloween|🎆 fireworks|🎇 sparkler"),
    ("object", "Objects & travel", "⌚ watch|📱 phone mobile|💻 laptop|⌨️ keyboard|🖥️ desktop computer monitor|🖨️ printer|🖱️ computer mouse|💾 floppy disk save|💿 cd disc|📷 camera|📸 camera flash photo|📹 video camera|🎥 movie camera|📞 telephone receiver|☎️ telephone|📺 tv television|📻 radio|🎙️ studio microphone|⏰ alarm clock|⏳ hourglass time|📡 satellite antenna|🔋 battery|🔌 plug|💡 light bulb idea|🔦 flashlight|🕯️ candle|💸 money wings|💵 dollar banknote|💶 euro banknote|💰 money bag|💳 credit card|💎 gem diamond|⚖️ balance scale|🔧 wrench|🔨 hammer|🛠️ tools|⛏️ pick|🔩 nut bolt|⚙️ gear settings|🧲 magnet|🔫 water pistol|💣 bomb|🧨 firecracker|🪓 axe|🔪 knife|🗡️ dagger|⚔️ crossed swords|🛡️ shield|⚰️ coffin|🔮 crystal ball|🔭 telescope|🔬 microscope|💊 pill|💉 syringe|🩹 adhesive bandage|🌡️ thermometer|🧹 broom|🧻 toilet paper|🚽 toilet|🚿 shower|🛁 bathtub|🧼 soap|🔑 key|🗝️ old key|🚪 door|🛋️ couch|🛏️ bed|🧸 teddy bear|🖼️ framed picture|🛍️ shopping bags|🛒 shopping cart|✉️ envelope mail|📩 envelope arrow|📦 package box|📫 mailbox|📝 memo note|📄 page document|📅 calendar date|📊 bar chart|📈 chart up|📉 chart down|📋 clipboard|📌 pushpin pin|📍 round pin location|📎 paperclip|✂️ scissors|🖊️ pen|✏️ pencil|🔍 magnifying glass search|🔒 locked|🔓 unlocked|🔔 bell|🔕 bell off mute|📢 loudspeaker|📣 megaphone|🗑️ wastebasket trash|🚗 car|🚕 taxi|🚌 bus|🏎️ racing car|🚓 police car|🚑 ambulance|🚒 fire engine|🚲 bicycle bike|🛵 scooter|🏍️ motorcycle|🚂 train|✈️ airplane plane|🚀 rocket|🛸 ufo flying saucer|🚁 helicopter|⛵ sailboat|🚢 ship|⚓ anchor|🏠 house home|🏢 office building|🏰 castle|🗽 statue of liberty|🗼 tower|🎡 ferris wheel|🗺️ world map|🧭 compass"),
    ("symbol", "Symbols", "✅ check mark done yes|☑️ ballot box check|✔️ check|❌ cross no wrong|❎ cross mark button|➕ plus|➖ minus|➗ divide|✖️ multiply|💯 hundred 100 points|💢 anger|💥 boom collision|💫 dizzy star|💦 sweat drops|💨 dash wind|💬 speech bubble|💭 thought bubble|🗯️ anger bubble|💤 zzz sleep|❓ question mark|❔ white question|❗ exclamation mark|❕ white exclamation|‼️ double exclamation|⁉️ exclamation question|⚠️ warning|🚫 prohibited no|⛔ no entry|🔞 no one under 18|📵 no phones|🔴 red circle|🟠 orange circle|🟡 yellow circle|🟢 green circle|🔵 blue circle|🟣 purple circle|⚫ black circle|⚪ white circle|🟥 red square|🟩 green square|🟦 blue square|⬛ black square|⬜ white square|🔺 red triangle up|🔻 red triangle down|🔶 orange diamond|🔷 blue diamond|♻️ recycle|⚜️ fleur de lis|🔱 trident|🔰 beginner|⭕ hollow red circle|🆗 ok button|🆕 new button|🆒 cool button|🆓 free button|🆙 up button|🆘 sos help|🔝 top arrow|🔜 soon arrow|🔙 back arrow|▶️ play|⏸️ pause|⏹️ stop|⏺️ record|⏭️ next track|⏮️ previous track|⏩ fast forward|⏪ rewind|🔀 shuffle|🔁 repeat|🔂 repeat one|🔼 up button|🔽 down button|➡️ right arrow|⬅️ left arrow|⬆️ up arrow|⬇️ down arrow|↗️ up right arrow|↘️ down right arrow|↙️ down left arrow|↖️ up left arrow|↕️ up down arrow|↔️ left right arrow|🔄 refresh arrows|🎵 music note|🎶 music notes|🔊 speaker loud|🔉 speaker medium|🔈 speaker low|🔇 muted speaker|ℹ️ information|🔤 abc letters|#️⃣ hash number sign|*️⃣ asterisk|0️⃣ zero|1️⃣ one|2️⃣ two|3️⃣ three|4️⃣ four|5️⃣ five|6️⃣ six|7️⃣ seven|8️⃣ eight|9️⃣ nine|🔟 ten|©️ copyright|®️ registered|™️ trade mark|💲 dollar sign|💱 currency exchange|☮️ peace|☯️ yin yang|♈ aries|♉ taurus|♊ gemini|♋ cancer|♌ leo|♍ virgo|♎ libra|♏ scorpio|♐ sagittarius|♑ capricorn|♒ aquarius|♓ pisces|🏁 checkered flag finish|🚩 red flag|🏳️ white flag|🏴 black flag|🏳️‍🌈 rainbow flag pride|🏴‍☠️ pirate flag"),
];

/// The category tabs' small line icons (ETAB), raw SVG.
pub const TAB_ICONS: [(&str, &str); 11] = [
    ("recent", r#"<svg viewBox="0 0 16 16"><circle cx="8" cy="8" r="5.8"/><path d="M8 4.9V8l2.1 1.4"/></svg>"#),
    ("smile", r#"<svg viewBox="0 0 16 16"><circle cx="8" cy="8" r="5.8"/><path d="M5.7 9.5a2.9 2.9 0 0 0 4.6 0"/><path d="M6.1 6.5h.01M9.9 6.5h.01" stroke-width="1.8"/></svg>"#),
    ("people", r#"<svg viewBox="0 0 16 16"><circle cx="8" cy="5.4" r="2.5"/><path d="M3.4 13.6a4.6 4.6 0 0 1 9.2 0"/></svg>"#),
    ("heart", r#"<svg viewBox="0 0 16 16"><path d="M8 13.2S2.6 10.1 2.6 6.3A2.75 2.75 0 0 1 8 5.1a2.75 2.75 0 0 1 5.4 1.2C13.4 10.1 8 13.2 8 13.2z"/></svg>"#),
    ("animal", r#"<svg viewBox="0 0 16 16"><path d="M8 8.4c1.9 0 3.6 1.7 3.6 3.2 0 1.2-1 1.7-2 1.7-.6 0-1-.3-1.6-.3s-1 .3-1.6.3c-1 0-2-.5-2-1.7 0-1.5 1.7-3.2 3.6-3.2z"/><circle cx="3.9" cy="7.1" r="1.1"/><circle cx="6.2" cy="4.3" r="1.1"/><circle cx="9.8" cy="4.3" r="1.1"/><circle cx="12.1" cy="7.1" r="1.1"/></svg>"#),
    ("food", r#"<svg viewBox="0 0 16 16"><path d="M3.4 6.6h7.8v2.9a3.6 3.6 0 0 1-3.6 3.6h-.6a3.6 3.6 0 0 1-3.6-3.6z"/><path d="M11.2 7.4h.9a1.6 1.6 0 0 1 0 3.2h-1.1"/><path d="M6 2.8v1.7M8.6 2.8v1.7"/></svg>"#),
    ("sport", r#"<svg viewBox="0 0 16 16"><circle cx="8" cy="8" r="5.8"/><path d="M2.5 6.4c2.6.3 4.6 2.5 5 7.3M13.5 9.6c-2.6-.3-4.6-2.5-5-7.3"/></svg>"#),
    ("object", r#"<svg viewBox="0 0 16 16"><path d="M5.9 11.1c0-1.6-2.1-2.6-2.1-5A4.2 4.2 0 0 1 8 2.3a4.2 4.2 0 0 1 4.2 3.8c0 2.4-2.1 3.4-2.1 5z"/><path d="M6.2 13.6h3.6"/></svg>"#),
    ("symbol", r#"<svg viewBox="0 0 16 16"><path d="M6.5 2.8l-1.1 10.4M10.6 2.8L9.5 13.2M3.2 6.1h10M2.8 9.9h10"/></svg>"#),
    ("search", r#"<svg viewBox="0 0 16 16"><circle cx="7" cy="7" r="4.3"/><path d="M10.2 10.2l3 3"/></svg>"#),
    ("back", r#"<svg viewBox="0 0 12 12"><path d="M7.5 2.5L4 6l3.5 3.5"/></svg>"#),
];
